apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: 
      selector:
        matchLabels:
          guestbook: enabled
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: "nginx-ingress-controller"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rputtapa/argocd.git
        targetRevision: master
        path: guestbook
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: guestbook
