apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress-controller
spec:
  generators:
  - clusters: 
      selector:
        matchLabels:
          ingress-nginx: "enabled"
  template:
    metadata:
      name: '{{name}}-nginx-ingress-controller' # 'name' field of the Secret
    spec:
      project: "nginx-ingress-controller"
      source:
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.1.1
        helm:
          releaseName: ingress-nginx
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
